### PR TITLE
nokura from OPS portal: Merge from master to live

### PR DESCRIPTION
**Pull request by webgenie**
## Summary

- Fix wrong translation for "Windows". "창" in Korean means "window" in English but "Windows" used in the document means Windows operating system, not windows on the wall. As "Windows" is a registered trademark of Microsoft, we use "Windows" as the name of the software product.

- Use the more well-known word (배포판 instead of 배포) which means Linux distro. The word "배포"  has a closer meaning of a verb or an action, rather than a noun. Switched it to a noun expression of "distribution", therefore.

### CODE REVIEW

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/programming-guide/enumeration-types.md](https://github.com/webgenie/docs.ko-kr/blob/update-core-get-started/docs/csharp/programming-guide/enumeration-types.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fenumeration-types.md)
[docs/csharp/programming-guide/strings/how-to-compare-strings.md](https://github.com/webgenie/docs.ko-kr/blob/update-core-get-started/docs/csharp/programming-guide/strings/how-to-compare-strings.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fstrings%2Fhow-to-compare-strings.md)

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fenumeration-types.md"></a>
### [docs/csharp/programming-guide/enumeration-types.md](https://github.com/webgenie/docs.ko-kr/blob/update-core-get-started/docs/csharp/programming-guide/enumeration-types.md)
 - **Line 43**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#1](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_1.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_1.cs.
 - **Line 73**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#4](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_2.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_2.cs.
 - **Line 80**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#3](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_3.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_3.cs.
 - **Line 89**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#2](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_4.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_4.cs.
 - **Line 93**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#6](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_5.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_5.cs.
 - **Line 97**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#7](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_6.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_6.cs.
 - **Line 104**: **[Error]** Unable to resolve  [!code-cs[csProgGuideEnums#5](../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_7.cs)]  

. Can not find reference ../../csharp/programming-guide/codesnippet/CSharp/enumeration-types_7.cs.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fstrings%2Fhow-to-compare-strings.md"></a>
### [docs/csharp/programming-guide/strings/how-to-compare-strings.md](https://github.com/webgenie/docs.ko-kr/blob/update-core-get-started/docs/csharp/programming-guide/strings/how-to-compare-strings.md)
 - **Line 51**: **[Error]** Unable to resolve  [!code-cs[csProgGuideStrings#11](../../../csharp/programming-guide/strings/codesnippet/CSharp/how-to-compare-strings_1.cs)]  

. Can not find reference ../../../csharp/programming-guide/strings/codesnippet/CSharp/how-to-compare-strings_1.cs.
 - **Line 56**: **[Error]** Unable to resolve  [!code-cs[csProgGuideStrings#31](../../../csharp/programming-guide/strings/codesnippet/CSharp/how-to-compare-strings_2.cs)]  

. Can not find reference ../../../csharp/programming-guide/strings/codesnippet/CSharp/how-to-compare-strings_2.cs.
 - **Line 61**: **[Error]** Unable to resolve  [!code-cs[csProgGuideStrings#32](../../../csharp/programming-guide/strings/codesnippet/CSharp/how-to-compare-strings_3.cs)]  

. Can not find reference ../../../csharp/programming-guide/strings/codesnippet/CSharp/how-to-compare-strings_3.cs.
 - **Line 69**: **[Warning]** Invalid file link:(~/docs/standard/base-types/comparing.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C13%5C716353f0-9988-e4f4-62fb-8a70ea7cfa15%5CPullRequest%5C201709131132449837-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TqLJVqsqpzrcm2vWTRBKYHRD9jDen3URm9h%2BzNMZrWc%3D&st=2017-09-13T11%3A33%3A27Z&se=2017-09-14T11%3A43%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @webgenie, we are still in discussing, will update the decision later soon. 
Please for future contributions use the "live" branch instead of "master".
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@nokura, @mairaw  Could you please change the base branch for this PR?

**Comment by mairaw** [comment]
Done @gosali!

**Comment by webgenie** [comment]
Glad to see this PR has been merged. Appreciate to everyone involved!

**Comment by gosali** [comment]
@webgenie , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
